#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

. /usr/local/bin/backend-functions

SCRIPT_NAME="SERVICE-XVFB"

WIDTH="${CAPTURE_WIDTH:-1920}"
HEIGHT="${CAPTURE_HEIGHT:-1080}"

log "$SCRIPT_NAME" "Starting Xvfb on ${DISPLAY} at ${WIDTH}x${HEIGHT}"

exec Xvfb "${DISPLAY}" -screen 0 "${WIDTH}x${HEIGHT}x24" -nolisten tcp -noreset
